version = 3
root    = "INJECT_PWD/out/var/lib/containerd"
state   = "INJECT_PWD/out/var/run/containerd"

[grpc]
	address = "/tmp/kata-shim-attempt-2/var/run/containerd/containerd.sock"


	# [plugins]
	# 	[plugins."io.containerd.cri.v1.runtime"]
	# 		[plugins."io.containerd.cri.v1.runtime".containerd]
	# 			default_runtime_name = "kata"
	# 			[plugins."io.containerd.cri.v1.runtime".containerd.runtimes]
	# 				[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.kata]
	# 					runtime_type = "io.containerd.kata.v2"
	# 					runtime_path = "INJECT_PWD/cmd/kata-shim-attempt-2/shim.sh"
	# 					[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.kata.options]
	# 						BinaryName = "INJECT_PWD/cmd/kata-shim-attempt-2/shim.sh"
