version = 3
root    = "/Users/dub6ix/Developer/tmp/ksa2/wrk/var/lib/containerd"
state   = "/Users/dub6ix/Developer/tmp/ksa2/wrk/var/run/containerd"

[grpc]
	address = "/Users/dub6ix/Developer/tmp/ksa2/var/run/containerd/containerd.sock"

[debug]
	level = "debug"

[plugins.linux]
	shim_debug = true
	# [plugins]
	# 	[plugins."io.containerd.cri.v1.runtime"]
	# 		[plugins."io.containerd.cri.v1.runtime".containerd]
	# 			default_runtime_name = "kata"
	# 			[plugins."io.containerd.cri.v1.runtime".containerd.runtimes]
	# 				[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.kata]
	# 					runtime_type = "io.containerd.kata.v2"
	# 					runtime_path = "INJECT_PWD/cmd/kata-shim-attempt-2/shim.sh"
	# 					[plugins."io.containerd.cri.v1.runtime".containerd.runtimes.kata.options]
	# 						BinaryName = "INJECT_PWD/cmd/kata-shim-attempt-2/shim.sh"
