version          = 3
root             = '/var/lib/containerd'
state            = '/var/run/containerd'
temp             = ''
plugin_dir       = ''
disabled_plugins = []
required_plugins = []
oom_score        = 0
imports          = []

[grpc]
	address               = '/var/run/containerd/containerd.sock'
	tcp_address           = ''
	tcp_tls_ca            = ''
	tcp_tls_cert          = ''
	tcp_tls_key           = ''
	uid                   = 0
	gid                   = 0
	max_recv_message_size = 16777216
	max_send_message_size = 16777216

[ttrpc]
	address = '/var/run/containerd/containerd.sock.ttrpc'
	uid     = 0
	gid     = 0

[debug]
	address = "/var/run/containerd/debug.sock"
	uid     = 0
	gid     = 0
	level   = ''
	format  = ''

[metrics]
	address        = ''
	grpc_histogram = false


[plugins]
	[plugins."io.containerd.grpc.v1.cri"]
		[plugins."io.containerd.grpc.v1.cri".containerd]
			default_runtime_name = "kata"
			[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
				[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
					runtime_type = "io.containerd.kata.v2"
					[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
						BinaryName = "./kata-containerd-shim-v2.sh"

[cgroup]
	path = ''

[stream_processors]

	[stream_processors.'io.containerd.ocicrypt.decoder.v1.tar']
		accepts = ['application/vnd.oci.image.layer.v1.tar+encrypted']
		returns = 'application/vnd.oci.image.layer.v1.tar'
		path = 'ctd-decoder'
		args = ['--decryption-keys-path', '/etc/containerd/ocicrypt/keys']
		env = [
			'OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf',
		]

	[stream_processors.'io.containerd.ocicrypt.decoder.v1.tar.gzip']
		accepts = ['application/vnd.oci.image.layer.v1.tar+gzip+encrypted']
		returns = 'application/vnd.oci.image.layer.v1.tar+gzip'
		path = 'ctd-decoder'
		args = ['--decryption-keys-path', '/etc/containerd/ocicrypt/keys']
		env = [
			'OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf',
		]
