[hypervisor.virtframework]
	kernel = "INJECT_PWD/vmlinuz-6.12.22-151"
	initrd = "INJECT_PWD/kata-alpine-3.18.initrd"
	# Path to QEMU binary (ensure this is the ARM64 QEMU for macOS, e.g. qemu-system-aarch64)
	# path = "/opt/homebrew/bin/qemu-system-aarch64"


	# # QEMU machine type for ARM64
	# machine_type = "virt"

	# # Use virtio-fs for shared file system
	# shared_fs = "virtio-fs"

	# # Path to virtiofsd (ensure this is available on your system)
	# virtio_fs_daemon = "/opt/homebrew/bin/virtiofsd"

	# # Default vCPUs and memory (adjust as needed)
	# default_vcpus     = 2
	# default_maxvcpus  = 4
	# default_memory    = 2048
	# default_maxmemory = 4096

	rootfs_type = "squashfs"
	# disable_block_device_use = true

	# Enable debug for troubleshooting
	enable_debug = true

# Use 'none' for internetworking_model for local macOS testing
[runtime]
	internetworking_model = "none"
	disable_guest_seccomp = true
	sandbox_cgroup_only   = true

[agent.kata]
	# Enable agent debug for troubleshooting
	enable_debug = true
	dial_timeout = 45

	# Add any additional settings as needed for your VM, kernel, or rootfs
	# For production, review and adjust all paths and security settings
