package main

import (
	"fmt"
	"log"
	"os"

	"github.com/go-openapi/loads"

	flag "github.com/spf13/pflag"

	"github.com/walteh/ec1/gen/firecracker-swagger-go/restapi"
	"github.com/walteh/ec1/gen/firecracker-swagger-go/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	var server *restapi.Server // make sure init is called

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  firecracker-api-server [OPTIONS]\n\n")

		title := "Firecracker API"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket."
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}
	// parse the CLI flags
	flag.Parse()

	impl := &operations.UnimplementedFirecrackerAPI{}

	api := operations.NewSwaggerAPI(swaggerSpec, impl)
	// get server with flag values filled out
	server = restapi.NewServer(api)
	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
